---
  server:
    port: 8080

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/task_tracker_repository
      username: postgres
      password: 4253
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true